name: flutter_application_1
description: A new Flutter project.

# Prevent accidental publishing to pub.dev
publish_to: "none"

# Version number for the app
version: 1.0.0+1

# Specify the environment and Dart SDK version
environment:
  sdk: ">=3.2.3 <4.0.0"

# Flutter dependencies and third-party packages
dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.2
  velocity_x: ^4.2.1  # Add any additional dependencies here
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  # http: ^1.2.2 

# Dev dependencies for testing and linting
dev_dependencies: 

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# Flutter-specific configurations
flutter:
  uses-material-design: true

  # Add any assets to be included in your app
  assets:
    - assets/images/
    - assets/files/
# Uncomment and configure fonts if you are using custom fonts in your app
# fonts:
#   - family: CustomFont
#     fonts:
#       - asset: fonts/CustomFont-Regular.ttf
